## builds an image without the ui part.
## ui can be run by using ng build --watch for development
version: "3.5"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
            - "80:80"
            - "443:443"
  hydraplay:
    # use platform linux/amd64 if you are running on apple siclicon ( ! requires rosetta ! )
    platform: linux/amd64
    privileged: true
    #image: mariolukas/hydraplay:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.ui.dev
      target: hydraplay
      args:
        SNAPCASTVERSION: 0.26.0
    container_name: hydraplay
    environment:
      PYTHONUNBUFFERED: 0
    ports:
      - 8080:8080
      - 1780:1780
      - 1704:1704
      - 1705:1705
      - 6680-6690:6680-6690
    volumes:
       # mount src folder for development
       - ./src/:/app/
       - ./hydra.private.json:/tmp/hydra.config.json
       - ./pipes/:/tmp/additional_streams
       - ./mp3:/media
    entrypoint: ["python3", "-u", "/app/hydraplay.sh", "--config", "/tmp/hydra.config.json", "--loglevel", "debug"]
