version: "3.5"
services:
  hydraplay:
    # use platform if you are running on apple m1 architecture ( requires rosetta )
    #platform: linux/amd64
    privileged: true
    build:
      context: docker/
      dockerfile: Dockerfile
      args:
        SNAPCASTVERSION: 0.26.0
        # use this for amd64 or armhf
        ARCH: amd64
    container_name: hydraplay
    ports:
      - 8080:8080
      - 1780:1780
      - 1704:1704
      - 1705:1705
      - 6600-6679:6600-6679
      - 6680-6690:6680-6690
    volumes:
       - ./src/:/hydraplay
       - ./hydra.private.json:/tmp/hydra.config.json