name: build raspberry pi os server image
on:
  push:
    tags:
      - '*'
jobs:
  build-pi-os-server-image:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Install build dependencies
        run: sudo apt-get -qq update
      - run: sudo apt-get -y install --no-install-recommends nodejs git vim parted binfmt-support ca-certificates qemu-utils kpartx quilt coreutils qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin rsync grep udev xz-utils curl xxd file kmod bc
      - name: ⬇ Checkout code
        uses: actions/checkout@v2
        with:
          path: hydraplay
      - run: git clone https://github.com/RPi-Distro/pi-gen
      - run: cd pi-gen && git fetch && git fetch --tags
      - run: git checkout 2021-10-30-raspios-bullseye && cd ..
      - name: Configure Image build environment
        run: cp -R hydraplay/.github/scripts/build-rpi-os/stage-hydraplay-server/ pi-gen/stage-hydraplay-server
      - run: cp hydraplay/.github/scripts/build-rpi-os/config.server pi-gen/config
      - name: Build image
        run: cd pi-gen && sudo ./build-docker.sh

