name: build docker image

on:
  workflow_run:
    workflows: ["build hydraplay release file"]
    types:
      - completed
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Get latest tag
        id: vars
        #run: echo ::set-output name=tag::${GITHUB_REF:10}
        run: echo tag=${GITHUB_REF:10} >> $GITHUB_OUTPUT

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/armhf
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hydraplay:${{ steps.vars.outputs.tag }},${{ secrets.DOCKERHUB_USERNAME }}/hydraplay:latest